dependencies:
  - name: zeebe-cluster-helm
    repository: "file://./zeebe-cluster-helm"
    version: 1.1.2-SNAPSHOT
  - name: zeebe-operate-helm
    repository: "file://./zeebe-operate-helm"
    version: 1.2.0-SNAPSHOT
    condition: "zeebe-operate-helm.enabled"
  - name: elasticsearch
    repository: http://helm.elastic.co
    version: 7.16.3
  - name: kibana
    repository: http://helm.elastic.co
    version: 7.16.3
    condition: "kibana.enabled"
  - name: mysql
    version: 9.4.8
    repository: "https://charts.bitnami.com/bitnami"
    alias: operationsmysql
    condition: "operations.mysql.enabled"
  - name: kong
    version: 2.13.1
    repository: https://charts.konghq.com
    condition: "kong.enabled"
  - name: keycloak
    version: 18.3.0
    repository: https://codecentric.github.io/helm-charts
    condition: "keycloak.enabled"
