name: Build and Package Helm Chart

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Lint Helm Chart
        run: |
          # Lint
          helm dependency update helm/ph-ee-engine
          helm lint helm/ph-ee-engine
      - name: Package Helm Chart
        run: |
          helm package helm/ph-ee-engine --destination ./artifacts
          ls -l ./artifacts
      - name: Publish Helm Chart
        uses: actions/upload-artifact@v4.3.1
        with:
          name: paymenthub
          path: ./artifacts/*
